on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-repo1:
    runs-on: ubuntu-latest
    steps:
      - run: npx lerna version
        working-directory: ./repo1

    
        