on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

name: release-repo2
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: test-repo2
        run: |
          echo "Release Repo 2 Tag: ${{ inputs.tag }}"