on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: node
          package-name: release-please-action

      - uses: mojojoji/monorepo/.github/workflows/release-repo1.yml@main
        if: ${{ steps.release.outputs['repo1--release_created'] }}
        with:
          tag: ${{ steps.release.outputs.repo1--tag_name }}


      - uses: mojojoji/monorepo/.github/workflows/release-repo2.yml@main
        if: ${{ steps.release.outputs['repo2--release_created'] }}
        with:
          tag: ${{ steps.release.outputs.repo2--tag_name }}
